services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: product_manager
      POSTGRES_USER: product_manager
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./massa:/opt/app/massa
    image: productmanager:latest
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/product_manager
      DATASOURCE_USERNAME: product_manager
      DATASOURCE_PASSWORD: localpassword
      INGESTION_FOLDER_LOCATION: /opt/app/massa
    ports:
      - "8080:8080"