name: Feature Branch Check & PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: product_manager
          POSTGRES_USER: product_manager
          POSTGRES_PASSWORD: localpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U your_db_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        env:
          PGPASSWORD: localpassword


      - name: Run Gradle Build and Tests
        run: ./gradlew clean build

  coverage:
    name: Generate JaCoCo Coverage Report
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: product_manager
          POSTGRES_USER: product_manager
          POSTGRES_PASSWORD: localpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U your_db_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        env:
          PGPASSWORD: localpassword

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacocoHtml

  open-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: coverage
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: 'feat: Automatic PR from feature branch - ${{ github.ref_name }}'
          body: |
            Este é um Pull Request automático gerado pela GitHub Actions.
            As verificações de build e cobertura foram concluídas com sucesso na branch `${{ github.ref_name }}`.

            Por favor, revise e merge se apropriado.
          labels: |
            automated-pr
            feature
          draft: false
