name: Feature Branch Check & PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle Build and Tests
        run: ./gradlew clean test --no-daemon

      - name: Upload JaCoCo Execution Data (.exec)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-exec-data


          path: build/jacoco/test.exec

  coverage:
    name: Generate JaCoCo Coverage Report
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download JaCoCo Execution Data (.exec)
        uses: actions/download-artifact@v4
        with:
          name: jacoco-exec-data
          path: build/jacoco

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacocoHtml

  open-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: coverage

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: 'feat: Automatic PR from feature branch - ${{ github.ref_name }}'
          body: |
            Este é um Pull Request automático gerado pela GitHub Actions.
            As verificações de build e cobertura foram concluídas com sucesso na branch `${{ github.ref_name }}`.
            
            Por favor, revise e merge se apropriado.
          update-branch: true
          labels: |
            automated-pr
            feature
